pub usingnamespace @cImport({
    // @cInclude("X11/Xatom.h");
    // @cInclude("X11/Xlib.h");
    // @cInclude("X11/cursorfont.h");
    // @cInclude("X11/keysym.h");
    // @cInclude("X11/Xft/Xft.h");
    // @cInclude("X11/XKBlib.h");
    @cInclude("sys/ioctl.h");
    @cInclude("xcb/xcb.h");
    @cInclude("xcb/xcb_cursor.h");
    @cInclude("xcb/xcb_keysyms.h");
    @cInclude("xcb/xcb_renderutil.h");
    @cInclude("xcb/xcb_xrm.h");
    @cInclude("xcb/render.h");
    @cInclude("locale.h");
    @cInclude("config.h");
    @cInclude("ft2build.h");
    @cInclude("fontconfig/fontconfig.h");
    // @cInclude("X11/Xlib-xcb.h");
    @cInclude("freetype/ftmm.h");
    @cInclude("freetype/ftoutln.h");
    @cInclude("freetype/ftsnames.h");
    @cInclude("freetype/ttnameid.h");
    @cInclude("sys/select.h");
});
