#!/bin/bash

echo "// Generated by check-features.sh"

linkrt=' -lrt '
testcc='cc'


cat <<EOF > /tmp/shm_test.c
#define _POSIX_C_SOURCE 200809L
#include <sys/mman.h>
#include <fcntl.h>
int main() { shm_open(0, 0, 0); return 0; }
EOF

if $testcc  -o /tmp/shm_test /tmp/shm_test.c $linkrt 2>/dev/null; then
    echo "pub const SHM_AVAILABLE =true;"
    echo "shm_open detected" >&2
else
    echo "pub const SHM_AVAILABLE =false;"
    echo "shm_open not detected" >&2
fi

cat <<EOF > /tmp/memfd_test.c
#define _GNU_SOURCE
#include <sys/mman.h>
int main() { memfd_create(0, 0); return 0; }
EOF

if  $testcc -o /tmp/memfd_test /tmp/memfd_test.c 2>/dev/null; then
    echo "pub const MEMFD_AVAILABLE =true;"
    echo "memfd_create detected" >&2
else
    echo "pub const MEMFD_AVAILABLE =false;"
    echo "memfd_create not detected" >&2
fi

rm -f /tmp/shm_test.c /tmp/shm_test /tmp/memfd_test.c /tmp/memfd_test
